document.write ("<h2>Entrada de Dados</h2>")

var numero1 = prompt("Digite o número 1");

var numero2 = prompt("Digite o número 2");

document.write("Número 1 = " + numero1 + "<br>")

document.write("Número 2 = " + numero2 + "<br>")

document.write ("<h2>Operações Aritméticas</h2>")
var resultado;

resultado = Number(numero1) + Number(numero2) 

document.write("A soma dos números é: " + resultado + "<br>")

document.write ("<h2>Operações Aritméticas</h2>")
var numeroA = 22;
var numeroB = -2;
var numeroC = 120;
var numeroD = 0.8333333333334;

document.write("A Soma dos Números é " + numeroA + "<br>");
document.write("A diferença dos Números é " + numeroB + "<br>");
document.write("O produto dos Números é " + numeroC + "<br>");
document.write("A divisão dos Números é " + numeroD + "<br>");